FROM golang:1.20-alpine AS builder
RUN apk update && apk add --no-cache make git
WORKDIR /go/src/github.com/forbole/callisto
COPY . ./
RUN go mod download
RUN make build

FROM alpine:latest
RUN apk add --no-cache ca-certificates curl bash
RUN curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
WORKDIR /callisto
COPY --from=builder /go/src/github.com/forbole/callisto/build/callisto /usr/bin/callisto
COPY config-thorchain.yaml /callisto/config.yaml
EXPOSE 3000
CMD [ "callisto", "parse", "/callisto/config.yaml" ]
