FROM --platform=$TARGETPLATFORM hasura/graphql-engine:v2.35.0.cli-migrations-v3

ENV HGE_BINARY=graphql-engine-pro

COPY hasura hasura

COPY docker-entrypoint.sh /bin/
RUN chmod +x /bin/docker-entrypoint.sh

ENTRYPOINT ["/bin/docker-entrypoint.sh"]

CMD $HGE_BINARY serve
